[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.0'
optimizer = true
optimizer_runs = 200

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@uniswap/v3-core/=lib/v3-core/'
]